/**
 * Batch experiments behind docs/observations.md.
 *
 * Runs many random soups through the same engine the website uses, detects when
 * each board becomes eventually periodic, and takes a census of the structures
 * that are left over. Requires Node 22.6+ for TypeScript imports.
 *
 *   node scripts/survey.mjs > docs/survey-output.md
 */
import { parseRule } from "../src/lib/life.ts";
import {
  artOf,
  canonical,
  classifyCluster,
  clusters,
  componentCount,
  nameOf,
  normalize,
  runSoup,
} from "./lib/ca.mjs";

const SIZE = 96;
const RUNS_PER_DENSITY = 12;
const MAX_GENERATIONS = 3000;
const DENSITIES = [0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.7, 0.8];

// --------------------------------------------------------------------------
// Experiments
// --------------------------------------------------------------------------

function densitySweep(ruleText) {
  const rule = parseRule(ruleText);
  const rows = [];
  for (const density of DENSITIES) {
    const settleTimes = [];
    const finalDensities = [];
    const periods = [];
    let extinct = 0;
    let unsettled = 0;

    for (let run = 0; run < RUNS_PER_DENSITY; run++) {
      const result = runSoup(rule, density, run * 7919 + Math.round(density * 1000), {
        size: SIZE,
        maxGenerations: MAX_GENERATIONS,
      });
      if (result.fate === "extinct") extinct++;
      else if (result.fate === "unsettled") unsettled++;
      else {
        settleTimes.push(result.enteredAt);
        periods.push(result.period);
        finalDensities.push(result.populations[result.populations.length - 1] / (SIZE * SIZE));
      }
    }
    const mean = (xs) => (xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : 0);
    const median = (xs) => {
      if (!xs.length) return 0;
      const s = [...xs].sort((a, b) => a - b);
      return s[s.length >> 1];
    };
    rows.push({
      density,
      extinct,
      unsettled,
      settled: settleTimes.length,
      medianSettle: median(settleTimes),
      meanFinalDensity: mean(finalDensities),
      maxPeriod: periods.length ? Math.max(...periods) : 0,
    });
  }
  return rows;
}

function census(ruleText, densities, runsEach) {
  const rule = parseRule(ruleText);
  const tally = new Map();
  let boards = 0;
  let totalClusters = 0;
  let compound = 0;

  for (const density of densities) {
    for (let run = 0; run < runsEach; run++) {
      const result = runSoup(rule, density, 100000 + run * 104729 + Math.round(density * 1000), {
        size: SIZE,
        maxGenerations: MAX_GENERATIONS,
      });
      if (result.fate !== "periodic") continue;
      boards++;
      for (const points of clusters(result.board)) {
        if (points.length > 40) continue;
        // A cluster groups everything within 2 cells so it can be simulated in
        // isolation, but only clusters holding one touching structure are
        // counted, otherwise four nearby blinkers read as one 12-cell object.
        if (componentCount(points) !== 1) {
          compound++;
          continue;
        }
        const info = classifyCluster(points, rule);
        if (!info.key) continue;
        totalClusters++;
        const label = `${nameOf(info.key, info.kind)}|${info.kind}|${info.key}`;
        tally.set(label, (tally.get(label) ?? 0) + 1);
      }
    }
  }
  return { tally, boards, totalClusters, compound };
}

// --------------------------------------------------------------------------

const started = Date.now();
console.log(`<!-- generated by scripts/survey.mjs on ${new Date().toISOString().slice(0, 10)} -->`);
console.log(`\nBoard ${SIZE}x${SIZE} torus, ${RUNS_PER_DENSITY} soups per density, cap ${MAX_GENERATIONS} generations.\n`);

for (const ruleText of ["B3/S23", "B36/S23"]) {
  console.log(`\n## Density sweep, ${ruleText}\n`);
  console.log("| initial density | extinct | reached a cycle | never settled | median generation the cycle starts | mean final density | longest period |");
  console.log("| --- | --- | --- | --- | --- | --- | --- |");
  for (const row of densitySweep(ruleText)) {
    console.log(
      `| ${(row.density * 100).toFixed(0)}% | ${row.extinct} | ${row.settled} | ${row.unsettled} | ${row.medianSettle} | ${(row.meanFinalDensity * 100).toFixed(2)}% | ${row.maxPeriod} |`,
    );
  }
}

for (const [ruleText, densities] of [
  ["B3/S23", [0.15, 0.3, 0.45]],
  ["B36/S23", [0.15, 0.3, 0.45]],
]) {
  console.log(`\n## Structure census, ${ruleText}\n`);
  const { tally, boards, totalClusters, compound } = census(ruleText, densities, 8);
  console.log(`${totalClusters} isolated structures on ${boards} settled boards; ${compound} touching groups were excluded.
`);
  console.log("| structure | kind | count | share | shape |");
  console.log("| --- | --- | --- | --- | --- |");
  const sorted = [...tally.entries()].sort((a, b) => b[1] - a[1]).slice(0, 14);
  for (const [label, count] of sorted) {
    const [name, kind, key] = label.split("|");
    const art = artOf(key).join("<br>").replace(/\./g, "&middot;").replace(/#/g, "&#9632;");
    console.log(`| ${name} | ${kind} | ${count} | ${((count / totalClusters) * 100).toFixed(1)}% | <code>${art}</code> |`);
  }
}


// --------------------------------------------------------------------------
// Moving objects: scan mid-run boards for glider-shaped clusters directly,
// because a glider on a torus keeps the board from repeating for a long time
// and those runs often exceed the generation cap.
// --------------------------------------------------------------------------

const GLIDER_KEY = canonical([
  [1, 0],
  [2, 1],
  [0, 2],
  [1, 2],
  [2, 2],
]);

function gliderScan(ruleText, densities, runsEach, generations) {
  const rule = parseRule(ruleText);
  const rows = [];
  for (const density of densities) {
    let boardsWithGlider = 0;
    let gliders = 0;
    for (let run = 0; run < runsEach; run++) {
      const result = runSoup(rule, density, 555000 + run * 15485863 + Math.round(density * 1000), {
        size: SIZE,
        maxGenerations: generations,
      });
      let here = 0;
      for (const points of clusters(result.board)) {
        if (points.length !== 5 || componentCount(points) !== 1) continue;
        if (canonical(normalize(points)) === GLIDER_KEY) here++;
      }
      gliders += here;
      if (here > 0) boardsWithGlider++;
    }
    rows.push({ density, boardsWithGlider, runsEach, gliders });
  }
  return rows;
}

for (const ruleText of ["B3/S23", "B36/S23"]) {
  console.log(`
## Moving objects after 1500 generations, ${ruleText}
`);
  console.log("| initial density | soups containing a glider | total gliders |");
  console.log("| --- | --- | --- |");
  for (const row of gliderScan(ruleText, [0.1, 0.2, 0.3, 0.45, 0.6], 10, 1500)) {
    console.log(`| ${(row.density * 100).toFixed(0)}% | ${row.boardsWithGlider} of ${row.runsEach} | ${row.gliders} |`);
  }
}

console.error(`survey finished in ${((Date.now() - started) / 1000).toFixed(0)}s`);
